version: '3'
services:
  eureka-server:
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    build: ./Eureka_Server/Eureka_Server
    networks:
      - app-network
  gateway-server:
    container_name: gateway-server
    restart: always
    ports:
      - "8888:8888"
    build: ./GateWay/GateWay
    environment:
      - EUREKA_SERVER=eureka-server
    networks:
      - app-network

  service-client:
    container_name: service-client
    restart: always
    ports:
      - "8088:8088"
    build:
      context: ./Client/Client
      dockerfile: Dockerfile
    environment:
      - EUREKA_SERVER=eureka-server
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    depends_on:
      - eureka-server
      - mysql
    networks:
      - app-network

  service-voiture:
    container_name: SERVICE-VOITURE
    restart: always
    ports:
      - "8089:8089"
    build:
      context: ./Voiture
      dockerfile: Dockerfile
    environment:
      - EUREKA_SERVER=eureka-server
      - SPRING_PROFILES_ACTIVE=docker
      - SERVICE-CLIENT=service-client
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    depends_on:
      - eureka-server
      - mysql
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

volumes:
  mysql:

networks:
  app-network:
    driver: bridge
